apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello
      app.kubernetes.io/component: hello
      app.kubernetes.io/instance: hello
    name: hello
  spec:
    replicas: 1
    selector:
      deploymentconfig: hello
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: hello
      spec:
        containers:
        - image: quay.io/redhattraining/hello-world-ngnix:v1.0
          name: hello
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
